### ISSUE TITLE
Missing Assembly or Directive

### ISSUE THREAD

**Issue by HegelianPoundCake** [wfowler1/Unity3D-BSP-Importer#18]
Getting this error when trying to install it, have attempted both manual through zip and through the github link. I also added the libBSP folder its asking about. 
Assets\Unity3D-BSP-Importer-master\Runtime\Extensions\BSPExtensions.cs(3,7): error CS0246: The type or namespace name 'LibBSP' could not be found (are you missing a using directive or an assembly reference?)

**Comment by wfowler1** [comment]
This should be fixed now :)
