### ISSUE TITLE
ArgumentOutOfRangeException on importing

### ISSUE THREAD

**Issue by tplathier** [wfowler1/Unity3D-BSP-Importer#2]
When importing certain maps (gm_construct (a default map from garry's mod) & rp_vespra_v4 are the ones I tried) the importer throw the following error in the console

`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
BSPImporter.BSPLoader.LoadBSP () (at Assets/Plugins/Unity3D-BSP-Importer-master/Util/BSPLoader.cs:171)
BSPImporterWindow.DrawImportButton () (at Assets/Plugins/Unity3D-BSP-Importer-master/Util/Editor/BSPImporterWindow.cs:101)
BSPImporterWindow.OnGUI () (at Assets/Plugins/Unity3D-BSP-Importer-master/Util/Editor/BSPImporterWindow.cs:40)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:359)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:353)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:329)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:374)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:341)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:298)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:483)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:466)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:447)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/Events/MouseCaptureDispatchingStrategy.cs:93)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:280)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:156)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:190)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:255)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:78)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)`

The prefab root and the worldspawn gameobjects are generated but empty
![image](https://user-images.githubusercontent.com/47102804/68083876-84b64800-fe2e-11e9-8b23-2b9fd5f9c3f8.png)

What is confusing is that importing gm_flatgrass, another default map from garry's mod works as intended and doesn't throw any error.

Double clicking the error in the console sends me to the line 171 of the BSPLoader.cs script if that is of any help identifying the issue.
Here are my import settings if that helps aswell, I'm using tga files for texture and they are stored inside my assets project folder
![image](https://user-images.githubusercontent.com/47102804/68083911-f098b080-fe2e-11e9-8a58-c59e9ea2726d.png)
And finally I'm using Unity 2019.2.5f1

I am a novice at meddling with both Unity and Source games so I can't figure out wether this is an issue with the importer script or a mistake of my own doing.
I really appreciate the tool you made as every other method of importing a .bsp map into Unity is a really painstaking effort!

Edit: Spacing

**Comment by tplathier** [comment]
Upon testing on an earlier version (2018.3.12f1) the exact same issue arise

**Comment by wfowler1** [comment]
Hello!

Sorry, I've had a million things going on and completely spaced on your
email. Sounds like you figured it out, but the VTFs are the actual
textures. I'd like to be able to convert VMTs to Unity materials but
haven't gotten to it yet.

I'll have to look into the exception, that call stack is just coming from
an exception handler I put in there to clean up the editor in case
something breaks. Thanks for letting me know, though.

**Comment by tplathier** [comment]
Great! I'm looking forward to a fix, thank you for the quick response!

**Comment by wfowler1** [comment]
Hello again,

I've been doing a significant amount of work elsewhere in the project
(mostly cleanups and QoL improvements) so I haven't gotten to look deeper
into this issue yet. At this point I just have a couple bugs to look into
before I finish things up, then this is my next priority.

Just wanted to let you know I haven't forgotten about this! Thanks for your
patience.

**Comment by tplathier** [comment]
This is great to hear! Thank for your hard work!
I'm looking forward to that aswell as the new QoL improvements!

**Comment by wfowler1** [comment]
Well, the QoL stuff is mostly for people working with LibBSP. So, me. But
it's stuff I've had on my roadmap that I've wanted to do for a while, on
top of working full-time and all that. But these are always projects I like
to work on. I hope other folks get good use out of it as well!

**Comment by wfowler1** [comment]
This should be fixed now.
