### ISSUE TITLE
Unit ratio from Trenchbroom to Unity

### ISSUE THREAD

**Issue by vncastanheira** [wfowler1/Unity3D-BSP-Importer#22]
I'm testing this library on a Unity project and trying to figure out what is the unit ration between the map editor and the engine. In order to keep the proportions correct, I'm trying to look for any setting in the code that tells the scale of the imported mesh.
I looked around and found an inch to meters constant but I'm not sure what is it for.

**Comment by wfowler1** [comment]
From what I've seen, most of these engines have the player height being about 72, which corresponds to a person 6 feet tall. So generally speaking, 1 unit = 1 inch. However in Unity, by default 1 unit = 1 meter. So when generating solids and positioning entities in Unity, I scale the positions of vertices by the conversion factor for inches to meters, `0.0254`.

As far as Trenchbroom, it really depends on the game you're building for. How tall is the player character, and how big does the level need to be around them?

I could easily turn the scaling into an option though, if for some reason the inches-to-meters conversion just isn't working out.

**Comment by vncastanheira** [comment]
I was comparing the measures between the standard character controller (1 unit on X and Z axis, 2 units on Y axis) and the player hull in Quake and it looked a bit off. After a while I found it on the code for adjusting the scale. So adding an option for scaling would be interesting, some other people could make use of that as well.
