### ISSUE TITLE
'Assets/Materials/*slime0.mat' is not a valid asset file name.

### ISSUE THREAD

**Issue by victorbstan** [wfowler1/Unity3D-BSP-Importer#23]
Is there an issue creating materials with `*` in their name perhaps? I got that error when trying to import `e1m1` as a test. Using Unity `2021.13.16f...`
```
'Assets/Materials/*slime0.mat' is not a valid asset file name.
```
<img width="1073" alt="Screenshot 2023-01-01 at 12 59 43 PM" src="https://user-images.githubusercontent.com/315297/210180457-f7c330b5-0db7-4e59-adc8-8b991ccc2440.png">

Tried to create one manually with `*` in filename and got a notification that it's a no no:
<img width="710" alt="Screenshot 2023-01-01 at 1 06 48 PM" src="https://user-images.githubusercontent.com/315297/210180649-98a093b5-7f89-43ad-b369-247873e11435.png">

**Comment by wfowler1** [comment]
Should be fixed as of https://github.com/wfowler1/Unity3D-BSP-Importer/commit/4e6f0dfbf54fe7adefd37a39157c6b066520aa5d
Update the package through Unity's Package Manager and give it a try!
