### ISSUE TITLE
this shit's useless

### ISSUE THREAD

**Issue by miaadev** [wfowler1/Unity3D-BSP-Importer#26]

**Comment by wfowler1** [comment]
Still more useful than this "issue" report.

**Comment by miaadev** [comment]
> Still more useful than this "issue" report.

all textures are blank

**Comment by tophermade** [comment]
I'd have helped you with that if you hadn't waded in with such a rude and "useless" bug report. Oh well. Good luck!

**Comment by miaadev** [comment]
> I'd have helped you with that if you hadn't waded in with such a rude and "useless" bug report. Oh well. Good luck!

I found another method anyway.
