### ISSUE TITLE
Curves and corridors not being converted properly

### ISSUE THREAD

**Issue by Wully616** [wfowler1/Unity3D-BSP-Importer#4]
I'm trying to convert a map from JKA. (ffa3.bsp)

Some areas don't get converted properly. I've tried increasing the curve detail but it doesn't make a difference. I'm not getting any errors

Expected: https://imgur.com/a/n0xoBoW
What im getting: https://imgur.com/a/TZ7gXp8

Any ideas?

**Comment by wfowler1** [comment]
It's likely there's something in this game specifically that's different, so the information isn't being read or interpreted properly. I'll have to do some research around this game specifically. Hopefully it's not too difficult to figure out.

Usually these kinds of surfaces are defined as a two-dimensional array of quadratic curves. When turning these into meshes, these quadratics need to be sampled at points along the curve to build triangles. The curve detail option just increases the number of samples on these curves and therefore the number of triangles generated, creating a smoother mesh. This is assuming, of course, the data for the curves is found and interpreted properly, which it doesn't seem to be.

**Comment by Wully616** [comment]
I understand, yeah the format for Jedi Knight is slightly different, I believe 2 lumps are treated different. 

The game was open sourced and I believe there might be answers in the code. There is a bsptool in the source code which has the structs for the BSP format. 
https://github.com/grayj/Jedi-Academy/tree/master/code/bspthing

I'm not super familar with BSP in general otherwise I would attempt a PR against your LibBSP.

**Comment by wfowler1** [comment]
Wow, that link is actually extremely helpful. I'll check it out over the weekend.

**Comment by Wully616** [comment]
Was the source code of any benefit to adding support for Jedi Knight maps?

**Comment by wfowler1** [comment]
Yes, but I've had a bit of a series of personal emergencies that came up. I haven't forgotten this! It's just a bit rough right now.

**Comment by Wully616** [comment]
No problem at all!
Life comes first.

I hope things get sorted for you soon
________________________________

**Comment by wfowler1** [comment]
There were actually two problems breaking this. It should be fixed if you pull LibBSP and the importer. Let me know!

**Comment by Wully616** [comment]
Amazing! Thank you.

At a cursory check, it does appear to have fixed the issue with curves

https://imgur.com/a/ivN0JDo

**Comment by Wully616** [comment]
Looks great, the textures look perfect too!
https://imgur.com/a/LlYlpgd
Thanks again
