### ISSUE TITLE
Combine by mesh and combine by entity produces overlapping UVs

### ISSUE THREAD

**Issue by Wully616** [wfowler1/Unity3D-BSP-Importer#6]
Hey!

 I've found when trying to bake lighting on the maps unity warns of overlapping UVs
Heres an example https://imgur.com/a/UgP9hoZ

You can see the lighting doesnt get applied properly because another part of the mesh is overlapping on the UVs

**Comment by Wully616** [comment]
Found a work around by exporting the mesh in unity using this package https://assetstore.unity.com/packages/essentials/fbx-exporter-101408 then within unity clicking the "Generate Lightmap UVs" in the model import, all of the textures seem to still look correct, and the lightmaps now bake nicely

**Comment by wfowler1** [comment]
Well, I'm not sure what exactly this means or how to fix it, but I'll look into it. It's a very strange error.

**Comment by lewa-j** [comment]
This means you need to generate uv2 for lightmaps.
