### ISSUE TITLE
Missing polygons in the geometry

### ISSUE THREAD

**Issue by gleblebedev** [wfowler1/Unity3D-BSP-Importer#8]
I've tried the importer on Quake DM3 level and some polygons seems to be missing:

![image](https://user-images.githubusercontent.com/2943937/97792064-281c7300-1bd1-11eb-9e89-e600a570599c.png)

**Comment by gleblebedev** [comment]
My old code import results for comparison:
![image](https://user-images.githubusercontent.com/2943937/98006118-c97e1180-1de9-11eb-9a7c-2e86025e81d0.png)

**Comment by wfowler1** [comment]
Sorry, I've been buried in work the past few days.

When you say "old code" what exactly do you mean? It's hard to see the problem with the wireframe, can you clarify a bit more what's missing?

**Comment by gleblebedev** [comment]
"Old code" - my own code to read BSP files. I ended up using it instead of your plugin.

> It's hard to see the problem with the wireframe, can you clarify a bit more what's missing?
Yes, it is hard to see :) This is how unity renders import result. Maybe it's another issue?

There are couple polygons missing. Do you have Quake1 available? Just try to import DM3 into Unity and you'll see the issue.

**Comment by wfowler1** [comment]
That wireframe material is what it uses if the texture could not be found. I think it's better than leaving everything blank or magenta.

As for the missing things, I'll have to look into it!

I'm curious about the code you have. I love hearing about other people's projects in things like this!

**Comment by bordaadam** [comment]
Could it be the same issue that I raised [here](https://github.com/wfowler1/Unity3D-BSP-Importer/issues/14)?

**Comment by wfowler1** [comment]
Yep, this was the same issue as #14. Closed by 173d0c439a7bb3a305be4c755ad8c3977da6e918
